AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
  RunRailsCops: true

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false