study:
  start:
    2012:
      1: <%= Date.new(2012,  9,  1) %>
      2: <%= Date.new(2013,  1,  13) %>
    2013:
      1: <%= Date.new(2013,  9,  1) %>
      2: <%= Date.new(2014,  1,  13) %>
    2014:
      1: <%= Date.new(2014,  9,  1) %>
      2: <%= Date.new(2015,  1,  13) %>
  end:
    2012:
      1: <%= Date.new(2012, 12, 31) %>
      2: <%= Date.new(2013,  6,  30) %>
    2013:
      1: <%= Date.new(2013, 12, 31) %>
      2: <%= Date.new(2014,  6,  30) %>
    2014:
      1: <%= Date.new(2014, 12, 31) %>
      2: <%= Date.new(2015,  6,  30) %>
